### PR TITLE
added code to print N fibonacci numbers

### PR DESCRIPTION
**Pull request by Jagdeep30**
Added a java code to print the fibonacci series till the input given by the user.

### CODE REVIEW

**Comment by akkupy** [comment]
Link the issue assigned to you

**Comment by Jagdeep30** [comment]
thnx

**Comment by akkupy** [comment]
Merging..You should mention the issue too in the pull request description

**Comment by Jagdeep30** [comment]
actually i am new and had no knowledge of that
i'll take care

**Pull request merged**
