### PR TITLE
Added Word Counter in python

### PR DESCRIPTION
**Pull request by akadeepesh**

### CODE REVIEW

**Comment by akkupy** [comment]
You are not assigned for this in the issue..
Request to be assigned in the ISSUE #33

**Comment by akadeepesh** [comment]
Is this filename ok?

**Comment by akkupy** [comment]
Update : Program should retreive input from user.

Don't use codes from the internet.

**Comment by akadeepesh** [comment]
sure

**Comment by akadeepesh** [comment]
what about this

**Comment by akkupy** [comment]
Good PR, Merging..

**Pull request merged**
