### PR TITLE
Fixed Median of Two Sorted Arrays in C++ #34

### PR DESCRIPTION
**Pull request by Aman5989**

### CODE REVIEW

**Comment by akkupy** [comment]
name the file as per the guidelines!

**Comment by akkupy** [comment]
@Aman5989 Place the file in the specific language folder!

**Comment by Aman5989** [comment]
changed the directory of the file also the name is as mentioned in the guidelines. please approve!

**Comment by akkupy** [comment]
Good PR ,  Merged.

**Pull request merged**
