### PR TITLE
adds OneHotEncoding modle for categorical data

### PR DESCRIPTION
**Pull request by Prisha-baveja**
I have successfully implemented a one hot encoding model on a categorical dataset, with customisable categories. It basically includes 3 categories which has ben vectorised into a binary format.

### CODE REVIEW

**Comment by akkupy** [comment]
Remove .DS_Store file from your PR

**Comment by akkupy** [comment]
Also link the issue you were working on

**Comment by Prisha-baveja** [comment]
Fixes #97 I have successfully implemented a one hot encoding model on a categorical dataset, with customisable categories. It basically includes 3 categories which has ben vectorised into a binary format. **Also I have removed the .DS_Store file from the PR.**

**Comment by akkupy** [comment]
PR ok

Merging..

**Pull request merged**
