### PR TITLE
Create mergeSort.c

### PR DESCRIPTION
**Pull request by Mohitraut07**
The provided C program implements the Merge Sort algorithm, a widely-used sorting technique. It recursively divides an array into smaller segments, sorts them individually, and then merges them back together to produce a sorted array. The program showcases this process and demonstrates sorting an array of integers in ascending order.

### CODE REVIEW

**Comment by Mohitraut07** [comment]
Please review this PR.

**Comment by Mohitraut07** [comment]
Also I have linked the issue.

**Comment by akkupy** [comment]
Please mention the issue in the PR!

**Comment by akkupy** [comment]
Merging it now

**Pull request merged**
