### PR TITLE
Added HTML code

### PR DESCRIPTION
**Pull request by Siddhesh179**
Fixed the issue of low contributions in Web development file by adding a simple html program consisting of hacktoberfest image titled Repository for Hacktoberfest 2023
#56

### CODE REVIEW

**Comment by akkupy** [comment]
html should be named index.html

Place your file in a separate folder inside the web folder.

**Comment by Siddhesh179** [comment]
please check,I have made the necessary changes.

**Comment by akkupy** [comment]
Would be better if you rename the folder from html to hacktoberfest_page

**Comment by Siddhesh179** [comment]
check now

**Comment by akkupy** [comment]
Merging..

**Pull request merged**
