### PR TITLE
added  selection_sort.cpp file

### PR DESCRIPTION
**Pull request by mohammedasimahmed**
I added  selection_sort.cpp file which contains the selection sort code , @akkupy could you please review it , issue link is https://github.com/tenzopy/codeIt/issues/157

### CODE REVIEW

**Comment by akkupy** [comment]
Please Link the issue assigned to you

**Comment by mohammedasimahmed** [comment]
> Please Link the issue assigned to you

@akkupy the issue was selection sort using c++ and the link to the issue is https://github.com/tenzopy/codeIt/issues/157

**Comment by vaibhav211002** [comment]
please assign this isssue to me.

**Comment by akkupy** [comment]
Merging..

**Pull request merged**
