### PR TITLE
new list containing only even nums

### PR DESCRIPTION
**Pull request by prabhatotato**
created a new list to store even elements.
added a for loop to select even elements from first lest.

### CODE REVIEW

**Comment by akkupy** [comment]
Link the issue assigned to you in the PR

**Comment by prabhatotato** [comment]
@akkupy link the issue? could you please explain in detail? I'm a beginner.

**Comment by akkupy** [comment]
You should mention the issue id that was assigned to you to do this work

**Comment by akkupy** [comment]
Have you created an issue ? If not create one issue now..and get assigned for this work..before merging

**Comment by prabhatotato** [comment]
@akkupy i was assigned this. It's issue #140

**Pull request closed without merging**
