### PR TITLE
Add bubble sort in Python

### PR DESCRIPTION
**Pull request by virejdasani**
Added new program of sorting in python

### CODE REVIEW

**Comment by akkupy** [comment]
Mwntion which sorting alogrithm used! and rename the file according to that

**Comment by virejdasani** [comment]
I used bubble sort algorithm to sort, I renamed the file too!

**Comment by akkupy** [comment]
Create a new issue on Bubble sort as per the guidelines. and link that issue with this PR.

**Comment by akkupy** [comment]
Good PR ,  Merging

**Pull request merged**
