### PR TITLE
Add Hero Section to the Component Folder

### LINKED ISSUE #174: Add Hero Section to Component Folder
**Title:** Add Hero Section to Component Folder

**Description:**
We need to enhance our application's user interface by adding a hero section to the component folder. A hero section is a visually appealing and informative element often placed at the top of a webpage to capture users' attention and provide important information or a call to action.

**Scope:**
This issue will involve creating a new component or modifying an existing one to implement the hero section. The hero section should be designed in a way that makes it easy to customize its content and appearance according to specific page requirements.

**Tasks:**
1. Create a new component for the hero section, or identify an existing component that can be modified for this purpose.
2. Design the hero section with attention to visual aesthetics and user experience.
3. Ensure the hero section is responsive and adapts well to different screen sizes and devices.
4. Implement the necessary logic and data bindings to dynamically update the hero section's content as needed.
5. Add appropriate documentation and comments to the code for future reference and maintenance.

**Acceptance Criteria:**
- The hero section component is successfully created or modified and added to the component folder.
- The hero section is visually appealing and aligns with our application's design guidelines.
- The hero section is responsive and works well on various screen sizes.
- The hero section can be easily customized with different content and styles.

**Additional Information:**
Please ensure that this change does not introduce any breaking changes to the existing codebase, and thorough testing should be conducted to validate its functionality.

### PR DESCRIPTION
**Pull request by umeshSinghVerma**
### Issue
Fixes #174 
### Description
This pull request introduces a new feature: the addition of a hero section to the component folder. The hero section will enhance the user interface and provide a more engaging experience.

### Changes Made
- Created a new "hero" component within the component folder.
- Designed and implemented the hero section UI.
- Integrated the hero component into the relevant parts of the application.

### Screenshots

(into moblile view)
image

(into desktop view)
image

Please review and provide feedback. Thank you!

### CODE REVIEW

**Comment by akkupy** [comment]
Please link the issue also

**Comment by umeshSinghVerma** [comment]
> Please link the issue also

@akkupy I have updated the comment by adding the issue, Sorry for the inconvenience

**Comment by umeshSinghVerma** [comment]
> Please link the issue also

@akkupy I have update the comment by adding the issue, Sorry for the inconvenience

**Comment by umeshSinghVerma** [comment]
Thanks :)

**Pull request merged**
