### PR TITLE
Created a Kotlin func to Calculate LCM

### PR DESCRIPTION
**Pull request by fvaysh**

### CODE REVIEW

**Comment by akkupy** [comment]
Link the issue assigned to you

**Comment by fvaysh** [comment]
Can you please let me know the fix needed as the code is running without issues on my compiler

**Comment by akkupy** [comment]
Just tell me the issue you were assigned to , for this work

**Comment by akkupy** [comment]
Code is working

I just need the issue inorder to merge it

**Comment by fvaysh** [comment]
The issue was to create a LCM calc in kotlin, inside the kotlin folder 
the issue was - codeIt/issues/132 (#132)
https://github.com/tenzopy/codeIt/issues/132

**Comment by akkupy** [comment]
Merging

**Pull request merged**
