### PR TITLE
Water-Snake-Gun-Added

### PR DESCRIPTION
**Pull request by capsy14**
## Pull Request
This pull request addresses issue #135 , which involves adding the Snake Water Gun game and ensuring that all its functionality is working correctly.
- Created the Snake Water Gun game in HTML, CSS, and JavaScript.
- Added images for the game options (Snake, Water, Gun).
- Implemented the game logic and functionality.
- Tested the game to ensure it works as expected.
### Screenshots
image
image

### CODE REVIEW

**Comment by akkupy** [comment]
PR is good...But switch the work to web folder

**Comment by capsy14** [comment]
Successfully switched to web folder :)

**Comment by akkupy** [comment]
@capsy14  Please check out #155 too

**Comment by akkupy** [comment]
Great PR, Merging... @capsy14 Please add the images and description in a README.md file in your folder also refer #155

**Pull request merged**
